from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext as build_ext_orig
import numpy
import numpy.f2py
import subprocess
import os
import platform
from pathlib import Path
import shutil
import sysconfig
import sys


# Default Fortran compiler is gfortran on every platform. Set
# ENDF_USERPY_USE_IFX=1 (or yes/true/on) on Windows to opt into the
# legacy Intel Fortran (ifx) build path instead.
USE_IFX = (
    sys.platform == 'win32'
    and os.environ.get('ENDF_USERPY_USE_IFX', '').strip().lower()
    in ('1', 'yes', 'true', 'on')
)


def _find_gfortran_libdir():
    """Locate the directory containing libgfortran on macOS.

    Homebrew installs gfortran's runtime under
    ``$(brew --prefix gcc)/lib/gcc/<N>/``, which clang's default linker
    search path does not include. Asking gfortran where the library
    lives via ``-print-file-name`` is the portable way to discover it.
    Returns None if gfortran is unavailable or does not know where its
    runtime lives.
    """
    if sys.platform != 'darwin':
        return None
    try:
        result = subprocess.check_output(
            ['gfortran', '-print-file-name=libgfortran.dylib'],
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    if os.path.isfile(result):
        return os.path.dirname(result)
    return None


# Force single-arch on macOS when the host Python is universal2 but the
# available gfortran is single-arch. Without this, distutils inherits
# the universal2 ARCHFLAGS, the Fortran .o files end up host-arch only,
# and the link step fails for the cross-arch slice. Respect any
# ARCHFLAGS the user has already set.
if (
    sys.platform == 'darwin'
    and not USE_IFX
    and 'ARCHFLAGS' not in os.environ
    and 'universal2' in sysconfig.get_platform()
):
    os.environ['ARCHFLAGS'] = f'-arch {platform.machine()}'


class build_ext(build_ext_orig):
    def initialize_options(self):
        super().initialize_options()
        # On Windows with gfortran, use the MinGW toolchain end-to-end so
        # the C compile + link step understands -lgfortran and finds
        # MinGW's libgfortran.dll.a. (The legacy ifx path keeps MSVC.)
        if sys.platform == 'win32' and not USE_IFX:
            self.compiler = 'mingw32'

    def run(self):
        # Compile the Fortran code
        if USE_IFX:
            subprocess.check_call(['ifx', '/c', 'endf_userpy/fortran/endf6.f90', '/Foendf_userpy/fortran/endf6.o'])
            subprocess.check_call(['ifx', '/c', 'endf_userpy/fortran/endf6-f2pywrappers.f', '/Foendf_userpy/fortran/endf6-f2pywrappers.o'])
        else:
            subprocess.check_call(['gfortran', '-fPIC', '-c', 'endf_userpy/fortran/endf6.f90', '-o', 'endf_userpy/fortran/endf6.o'])
            subprocess.check_call(['gfortran', '-fPIC', '-c', 'endf_userpy/fortran/endf6-f2pywrappers.f', '-o', 'endf_userpy/fortran/endf6-f2pywrappers.o'])
        # Call the original build_ext
        super().run()

        lib_ext = sysconfig.get_config_var('EXT_SUFFIX')
        build_lib_dir = os.path.join(self.build_lib, 'endf_userpy/fortran')
        shared_lib_name = 'endf6' + lib_ext
        shared_lib_src = self.get_ext_fullpath('endf6')
        shared_lib_dst = os.path.join(build_lib_dir, shared_lib_name)
        # Move the shared library to the correct location
        if os.path.exists(shared_lib_src):
            if not os.path.exists(build_lib_dir):
                os.makedirs(build_lib_dir)
            shutil.move(shared_lib_src, shared_lib_dst)
        else:
            raise Exception("not working")
            print(f"Warning: Shared library {shared_lib_src} not found")


f2py_include_path = numpy.f2py.get_include()
fortranobject_c_path = os.path.join(f2py_include_path, 'fortranobject.c')


def prepare_endf6module_c(source_file, dest_file, on_windows):
    with open(source_file, 'r', newline='') as f:
        cont = f.readlines()
    if on_windows:
        prepro = [
            '// The following preprocessor directive is necessary\n',
            '// on Windows to ensure that symbol names in the object files\n',
            '// generated by the Intel Fortran compiler (ifx) can be\n',
            '// found by the Microsoft Visual C++ linker\n',
            '// here comes the directive\n',
            '#define NO_APPEND_FORTRAN\n',
            '#define UPPERCASE_FORTRAN\n',
            '\n',
        ]
        cont = prepro + cont
    with open(dest_file, 'w', newline='') as f:
        f.writelines(cont)


# Define the extension module
c_module_template_file = Path('endf_userpy') / 'fortran' / 'endf6module.c'
c_module_file = Path('endf_userpy') / 'fortran' / 'endf6module_active.c'
if USE_IFX:
    extra_link_args = []
    add_libraries = []
    prepare_endf6module_c(c_module_template_file, c_module_file, True)
else:
    extra_link_args = ['-lgfortran']
    add_libraries = ['gfortran']
    prepare_endf6module_c(c_module_template_file, c_module_file, False)


# Hand the linker an explicit -L for Homebrew's gfortran runtime on
# macOS; clang would not find it via its default search path.
extra_library_dirs = []
if not USE_IFX:
    gfortran_libdir = _find_gfortran_libdir()
    if gfortran_libdir is not None:
        extra_library_dirs.append(gfortran_libdir)


extension = Extension(
    'endf6',
    sources=[
        fortranobject_c_path,
        str(c_module_file),  # Use the correct file generated by numpy.f2py
    ],
    extra_objects=[
        'endf_userpy/fortran/endf6.o',
        'endf_userpy/fortran/endf6-f2pywrappers.o'
    ],
    include_dirs=[
        numpy.get_include(),
        numpy.f2py.get_include(),
    ],
    library_dirs=extra_library_dirs,
    libraries=add_libraries,
    extra_link_args=extra_link_args,
)

setup(
    name='endf-userpy',
    version='0.1.0a3',
    author='Georg Schnabel, Daniel Lopez Aldama',
    license='MIT',
    url='https://github.com/IAEA-NDS/endf-userpy',
    project_urls={
        'Repository': 'https://github.com/IAEA-NDS/endf-userpy',
        'Issues': 'https://github.com/IAEA-NDS/endf-userpy/issues',
    },
    packages=find_packages(include=['endf_userpy', 'endf_userpy.*']),
    ext_modules=[extension],
    cmdclass={'build_ext': build_ext},
    python_requires='>=3.9',
    install_requires=[
        'numpy>=2.0',
        'scipy',
        'endf_parserpy',
    ],
    description='High-level interpretation of ENDF-6 data',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Operating System :: POSIX :: Linux',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Fortran',
        'Programming Language :: C',
        'Topic :: Scientific/Engineering :: Physics',
    ],
)
