from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext as build_ext_orig
import numpy
import subprocess
import os
from pathlib import Path
import shutil
import sysconfig
import sys


class build_ext(build_ext_orig):
    def run(self):
        # Compile the Fortran code
        if sys.platform != 'win32':
            subprocess.check_call(['gfortran', '-fPIC', '-c', 'endf_userpy/fortran/endf6.f90', '-o', 'endf_userpy/fortran/endf6.o'])
            subprocess.check_call(['gfortran', '-fPIC', '-c', 'endf_userpy/fortran/endf6-f2pywrappers.f', '-o', 'endf_userpy/fortran/endf6-f2pywrappers.o'])
        else:
            subprocess.check_call(['ifx', '/c', 'endf_userpy/fortran/endf6.f90', '/Foendf_userpy/fortran/endf6.o'])
            subprocess.check_call(['ifx', '/c', 'endf_userpy/fortran/endf6-f2pywrappers.f', '/Foendf_userpy/fortran/endf6-f2pywrappers.o'])
        # Call the original build_ext
        super().run()

        lib_ext = sysconfig.get_config_var('EXT_SUFFIX')
        build_lib_dir = os.path.join(self.build_lib, 'endf_userpy/fortran')
        shared_lib_name = 'endf6' + lib_ext
        shared_lib_src = self.get_ext_fullpath('endf6')
        shared_lib_dst = os.path.join(build_lib_dir, shared_lib_name)
        # Move the shared library to the correct location
        if os.path.exists(shared_lib_src):
            if not os.path.exists(build_lib_dir):
                os.makedirs(build_lib_dir)
            shutil.move(shared_lib_src, shared_lib_dst)
        else:
            raise Exception("not working")
            print(f"Warning: Shared library {shared_lib_src} not found")


f2py_include_path = numpy.f2py.get_include()
fortranobject_c_path = os.path.join(f2py_include_path, 'fortranobject.c')


def prepare_endf6module_c(source_file, dest_file, on_windows):
    with open(source_file, 'r', newline='') as f:
        cont = f.readlines()
    if on_windows:
        prepro = [
            '// The following preprocessor directive is necessary\n',
            '// on Windows to ensure that symbol names in the object files\n',
            '// generated by the Intel Fortran compiler (ifx) can be\n',
            '// found by the Microsoft Visual C++ linker\n',
            '// here comes the directive\n',
            '#define NO_APPEND_FORTRAN\n',
            '#define UPPERCASE_FORTRAN\n',
            '\n',
        ]
        cont = prepro + cont
    with open(dest_file, 'w', newline='') as f:
        f.writelines(cont)


# Define the extension module
c_module_template_file = Path('endf_userpy') / 'fortran' / 'endf6module.c'
c_module_file = Path('endf_userpy') / 'fortran' / 'endf6module_active.c'
if sys.platform != 'win32':
    extra_link_args = ['-lgfortran']
    add_libraries = ['gfortran']
    prepare_endf6module_c(c_module_template_file, c_module_file, False)
else:
    extra_link_args = []
    add_libraries = []
    prepare_endf6module_c(c_module_template_file, c_module_file, True)

extension = Extension(
    'endf6',
    sources=[
        fortranobject_c_path,
        str(c_module_file),  # Use the correct file generated by numpy.f2py
    ],
    extra_objects=[
        'endf_userpy/fortran/endf6.o',
        'endf_userpy/fortran/endf6-f2pywrappers.o'
    ],
    include_dirs=[
        numpy.get_include(),
        numpy.f2py.get_include(),
    ],
    libraries=add_libraries,
    extra_link_args=extra_link_args,
)

setup(
    name='endf-userpy',
    version='0.0',
    #packages=['endf_userpy'],
    packages=find_packages(),
    ext_modules=[extension],
    cmdclass={'build_ext': build_ext},
    install_requires=[
        'numpy'
    ],
    description='High-level interpretation of ENDF-6 data',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Fortran',
        'Programming Language :: C',
        'Operating System :: OS Independent',
    ],
)
