from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext as build_ext_orig
import numpy
import subprocess
import os
import shutil
import sysconfig
import sys


class build_ext(build_ext_orig):
    def run(self):
        # Compile the Fortran code
        if sys.platform != 'win32':
            subprocess.check_call(['gfortran', '-c', 'endf_userpy/fortran/endf6.f90', '-o', 'endf_userpy/fortran/endf6.o'])
            subprocess.check_call(['gfortran', '-c', 'endf_userpy/fortran/endf6-f2pywrappers.f', '-o', 'endf_userpy/fortran/endf6-f2pywrappers.o'])
        else:
            subprocess.check_call(['ifx', '/c', 'endf_userpy/fortran/endf6.f90', '/Foendf_userpy/fortran/endf6.o'])
            subprocess.check_call(['ifx', '/c', 'endf_userpy/fortran/endf6-f2pywrappers.f', '/Foendf_userpy/fortran/endf6-f2pywrappers.o'])
        # Call the original build_ext
        super().run()

        lib_ext = sysconfig.get_config_var('EXT_SUFFIX')
        build_lib_dir = os.path.join(self.build_lib, 'endf_userpy/fortran')
        shared_lib_name = 'endf6' + lib_ext 
        shared_lib_src = self.get_ext_fullpath('endf6') 
        shared_lib_dst = os.path.join(build_lib_dir, shared_lib_name)
        # Move the shared library to the correct location
        if os.path.exists(shared_lib_src):
            if not os.path.exists(build_lib_dir):
                os.makedirs(build_lib_dir)
            shutil.move(shared_lib_src, shared_lib_dst)
        else:
            raise Exception("not working")
            print(f"Warning: Shared library {shared_lib_src} not found")


f2py_include_path = numpy.f2py.get_include()
fortranobject_c_path = os.path.join(f2py_include_path, 'fortranobject.c')


# Define the extension module
if sys.platform != 'win32':
    extra_link_args = ['-lgfortran']
    add_libraries = ['gfortran']
    c_module_file = 'endf6module.c'
else:
    extra_link_args = []
    add_libraries = []
    c_module_file = 'endf6module.c'

extension = Extension(
    'endf6',
    sources=[
        fortranobject_c_path,
        f'endf_userpy/fortran/{c_module_file}',  # Use the correct file generated by numpy.f2py
    ],
    extra_objects=[
        'endf_userpy/fortran/endf6.o',
        'endf_userpy/fortran/endf6-f2pywrappers.o'
    ],
    include_dirs=[
        numpy.get_include(),
        numpy.f2py.get_include(),
    ],
    libraries=add_libraries,
    extra_link_args=extra_link_args,
)

setup(
    name='endf-userpy',
    version='0.0',
    packages=['endf_userpy'],
    ext_modules=[extension],
    cmdclass={'build_ext': build_ext},
    install_requires=[
        'numpy'
    ],
    description='High-level interpretation of ENDF-6 data',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Fortran',
        'Programming Language :: C',
        'Operating System :: OS Independent',
    ],
)
