/* File: endf6module.c
 * This file is auto-generated with f2py (version:2.1.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Sep 19 18:11:29 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *endf6_error;
static PyObject *endf6_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(endf6_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = endf6_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = endf6_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(mf4_get_leg,MF4_GET_LEG)(double*,double*,double*,double*,int*,double*,double*,int*,double*,double*,int*,int*,double*,int*,double*,int*,double*);
extern void F_WRAPPEDFUNC(yintp,YINTP)(double*,double*,double*,double*,double*,int*,double*);
extern void F_WRAPPEDFUNC(yleg,YLEG)(double*,double*,double*,int*);
extern void F_FUNC(legndr,LEGNDR)(double*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** mf4_get_leg ********************************/
static char doc_f2py_rout_endf6_mf4_get_leg[] = "\
mf4_get_leg(awr,awi,awp,q,lct,e1,a1,nl1,e2,a2,nl2,ilaw,e,xmu,nmu,f4,[ne])\n\nWrapper for ``mf4_get_leg``.\
\n\nParameters\n----------\n"
"awr : input float\n"
"awi : input float\n"
"awp : input float\n"
"q : input float\n"
"lct : input int\n"
"e1 : input float\n"
"a1 : input rank-1 array('d') with bounds (*)\n"
"nl1 : input int\n"
"e2 : input float\n"
"a2 : input rank-1 array('d') with bounds (*)\n"
"nl2 : input int\n"
"ilaw : input int\n"
"e : input rank-1 array('d') with bounds (*)\n"
"xmu : input rank-1 array('d') with bounds (*)\n"
"nmu : input int\n"
"f4 : input rank-2 array('d') with bounds (ne,*)\n"
"\nOther Parameters\n----------------\n"
"ne : input int, optional\n    Default: shape(f4, 0)";
/* extern void F_FUNC_US(mf4_get_leg,MF4_GET_LEG)(double*,double*,double*,double*,int*,double*,double*,int*,double*,double*,int*,int*,double*,int*,double*,int*,double*); */
static PyObject *f2py_rout_endf6_mf4_get_leg(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,double*,double*,int*,double*,double*,int*,int*,double*,int*,double*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double awr = 0;
    PyObject *awr_capi = Py_None;
    double awi = 0;
    PyObject *awi_capi = Py_None;
    double awp = 0;
    PyObject *awp_capi = Py_None;
    double q = 0;
    PyObject *q_capi = Py_None;
    int lct = 0;
    PyObject *lct_capi = Py_None;
    double e1 = 0;
    PyObject *e1_capi = Py_None;
    double *a1 = NULL;
    npy_intp a1_Dims[1] = {-1};
    const int a1_Rank = 1;
    PyArrayObject *capi_a1_as_array = NULL;
    int capi_a1_intent = 0;
    PyObject *a1_capi = Py_None;
    int nl1 = 0;
    PyObject *nl1_capi = Py_None;
    double e2 = 0;
    PyObject *e2_capi = Py_None;
    double *a2 = NULL;
    npy_intp a2_Dims[1] = {-1};
    const int a2_Rank = 1;
    PyArrayObject *capi_a2_as_array = NULL;
    int capi_a2_intent = 0;
    PyObject *a2_capi = Py_None;
    int nl2 = 0;
    PyObject *nl2_capi = Py_None;
    int ilaw = 0;
    PyObject *ilaw_capi = Py_None;
    double *e = NULL;
    npy_intp e_Dims[1] = {-1};
    const int e_Rank = 1;
    PyArrayObject *capi_e_as_array = NULL;
    int capi_e_intent = 0;
    PyObject *e_capi = Py_None;
    int ne = 0;
    PyObject *ne_capi = Py_None;
    double *xmu = NULL;
    npy_intp xmu_Dims[1] = {-1};
    const int xmu_Rank = 1;
    PyArrayObject *capi_xmu_as_array = NULL;
    int capi_xmu_intent = 0;
    PyObject *xmu_capi = Py_None;
    int nmu = 0;
    PyObject *nmu_capi = Py_None;
    double *f4 = NULL;
    npy_intp f4_Dims[2] = {-1, -1};
    const int f4_Rank = 2;
    PyArrayObject *capi_f4_as_array = NULL;
    int capi_f4_intent = 0;
    PyObject *f4_capi = Py_None;
    static char *capi_kwlist[] = {"awr","awi","awp","q","lct","e1","a1","nl1","e2","a2","nl2","ilaw","e","xmu","nmu","f4","ne",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOO|O:endf6.mf4_get_leg",\
        capi_kwlist,&awr_capi,&awi_capi,&awp_capi,&q_capi,&lct_capi,&e1_capi,&a1_capi,&nl1_capi,&e2_capi,&a2_capi,&nl2_capi,&ilaw_capi,&e_capi,&xmu_capi,&nmu_capi,&f4_capi,&ne_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a1 */
    ;
    capi_a1_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.mf4_get_leg: failed to create array from the 7th argument `a1`";
    capi_a1_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a1_Dims,a1_Rank,  capi_a1_intent,a1_capi,capi_errmess);
    if (capi_a1_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a1 = (double *)(PyArray_DATA(capi_a1_as_array));

    /* Processing variable a2 */
    ;
    capi_a2_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.mf4_get_leg: failed to create array from the 10th argument `a2`";
    capi_a2_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a2_Dims,a2_Rank,  capi_a2_intent,a2_capi,capi_errmess);
    if (capi_a2_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a2 = (double *)(PyArray_DATA(capi_a2_as_array));

    /* Processing variable e */
    ;
    capi_e_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.mf4_get_leg: failed to create array from the 13rd argument `e`";
    capi_e_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,e_Dims,e_Rank,  capi_e_intent,e_capi,capi_errmess);
    if (capi_e_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        e = (double *)(PyArray_DATA(capi_e_as_array));

    /* Processing variable xmu */
    ;
    capi_xmu_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.mf4_get_leg: failed to create array from the 14th argument `xmu`";
    capi_xmu_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,xmu_Dims,xmu_Rank,  capi_xmu_intent,xmu_capi,capi_errmess);
    if (capi_xmu_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        xmu = (double *)(PyArray_DATA(capi_xmu_as_array));

    /* Processing variable f4 */
    ;
    capi_f4_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.mf4_get_leg: failed to create array from the 16th argument `f4`";
    capi_f4_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,f4_Dims,f4_Rank,  capi_f4_intent,f4_capi,capi_errmess);
    if (capi_f4_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        f4 = (double *)(PyArray_DATA(capi_f4_as_array));

    /* Processing variable awr */
        f2py_success = double_from_pyobj(&awr,awr_capi,"endf6.mf4_get_leg() 1st argument (awr) can't be converted to double");
    if (f2py_success) {
    /* Processing variable awi */
        f2py_success = double_from_pyobj(&awi,awi_capi,"endf6.mf4_get_leg() 2nd argument (awi) can't be converted to double");
    if (f2py_success) {
    /* Processing variable awp */
        f2py_success = double_from_pyobj(&awp,awp_capi,"endf6.mf4_get_leg() 3rd argument (awp) can't be converted to double");
    if (f2py_success) {
    /* Processing variable q */
        f2py_success = double_from_pyobj(&q,q_capi,"endf6.mf4_get_leg() 4th argument (q) can't be converted to double");
    if (f2py_success) {
    /* Processing variable lct */
        f2py_success = int_from_pyobj(&lct,lct_capi,"endf6.mf4_get_leg() 5th argument (lct) can't be converted to int");
    if (f2py_success) {
    /* Processing variable e1 */
        f2py_success = double_from_pyobj(&e1,e1_capi,"endf6.mf4_get_leg() 6th argument (e1) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nl1 */
        f2py_success = int_from_pyobj(&nl1,nl1_capi,"endf6.mf4_get_leg() 8th argument (nl1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable e2 */
        f2py_success = double_from_pyobj(&e2,e2_capi,"endf6.mf4_get_leg() 9th argument (e2) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nl2 */
        f2py_success = int_from_pyobj(&nl2,nl2_capi,"endf6.mf4_get_leg() 11st argument (nl2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ilaw */
        f2py_success = int_from_pyobj(&ilaw,ilaw_capi,"endf6.mf4_get_leg() 12nd argument (ilaw) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nmu */
        f2py_success = int_from_pyobj(&nmu,nmu_capi,"endf6.mf4_get_leg() 15th argument (nmu) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ne */
    if (ne_capi == Py_None) ne = shape(f4, 0); else
        f2py_success = int_from_pyobj(&ne,ne_capi,"endf6.mf4_get_leg() 1st keyword (ne) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(f4, 0) == ne,"shape(f4, 0) == ne","1st keyword ne","mf4_get_leg:ne=%d",ne) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&awr,&awi,&awp,&q,&lct,&e1,a1,&nl1,&e2,a2,&nl2,&ilaw,e,&ne,xmu,&nmu,f4);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKSCALAR(shape(f4, 0) == ne)*/
    } /*if (f2py_success) of ne*/
    /* End of cleaning variable ne */
    } /*if (f2py_success) of nmu*/
    /* End of cleaning variable nmu */
    } /*if (f2py_success) of ilaw*/
    /* End of cleaning variable ilaw */
    } /*if (f2py_success) of nl2*/
    /* End of cleaning variable nl2 */
    } /*if (f2py_success) of e2*/
    /* End of cleaning variable e2 */
    } /*if (f2py_success) of nl1*/
    /* End of cleaning variable nl1 */
    } /*if (f2py_success) of e1*/
    /* End of cleaning variable e1 */
    } /*if (f2py_success) of lct*/
    /* End of cleaning variable lct */
    } /*if (f2py_success) of q*/
    /* End of cleaning variable q */
    } /*if (f2py_success) of awp*/
    /* End of cleaning variable awp */
    } /*if (f2py_success) of awi*/
    /* End of cleaning variable awi */
    } /*if (f2py_success) of awr*/
    /* End of cleaning variable awr */
    if((PyObject *)capi_f4_as_array!=f4_capi) {
        Py_XDECREF(capi_f4_as_array); }
    }  /* if (capi_f4_as_array == NULL) ... else of f4 */
    /* End of cleaning variable f4 */
    if((PyObject *)capi_xmu_as_array!=xmu_capi) {
        Py_XDECREF(capi_xmu_as_array); }
    }  /* if (capi_xmu_as_array == NULL) ... else of xmu */
    /* End of cleaning variable xmu */
    if((PyObject *)capi_e_as_array!=e_capi) {
        Py_XDECREF(capi_e_as_array); }
    }  /* if (capi_e_as_array == NULL) ... else of e */
    /* End of cleaning variable e */
    if((PyObject *)capi_a2_as_array!=a2_capi) {
        Py_XDECREF(capi_a2_as_array); }
    }  /* if (capi_a2_as_array == NULL) ... else of a2 */
    /* End of cleaning variable a2 */
    if((PyObject *)capi_a1_as_array!=a1_capi) {
        Py_XDECREF(capi_a1_as_array); }
    }  /* if (capi_a1_as_array == NULL) ... else of a1 */
    /* End of cleaning variable a1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of mf4_get_leg *****************************/

/*********************************** yintp ***********************************/
static char doc_f2py_rout_endf6_yintp[] = "\
yintp = yintp(x1,y1,x2,y2,i,x)\n\nWrapper for ``yintp``.\
\n\nParameters\n----------\n"
"x1 : input float\n"
"y1 : input float\n"
"x2 : input float\n"
"y2 : input float\n"
"i : input int\n"
"x : input float\n"
"\nReturns\n-------\n"
"yintp : float";
/* extern void F_WRAPPEDFUNC(yintp,YINTP)(double*,double*,double*,double*,double*,int*,double*); */
static PyObject *f2py_rout_endf6_yintp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double yintp = 0;
    double x1 = 0;
    PyObject *x1_capi = Py_None;
    double y1 = 0;
    PyObject *y1_capi = Py_None;
    double x2 = 0;
    PyObject *x2_capi = Py_None;
    double y2 = 0;
    PyObject *y2_capi = Py_None;
    int i = 0;
    PyObject *i_capi = Py_None;
    double x = 0;
    PyObject *x_capi = Py_None;
    static char *capi_kwlist[] = {"x1","y1","x2","y2","i","x",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOO|:endf6.yintp",\
        capi_kwlist,&x1_capi,&y1_capi,&x2_capi,&y2_capi,&i_capi,&x_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable yintp */
    /* Processing variable x1 */
        f2py_success = double_from_pyobj(&x1,x1_capi,"endf6.yintp() 1st argument (x1) can't be converted to double");
    if (f2py_success) {
    /* Processing variable y1 */
        f2py_success = double_from_pyobj(&y1,y1_capi,"endf6.yintp() 2nd argument (y1) can't be converted to double");
    if (f2py_success) {
    /* Processing variable x2 */
        f2py_success = double_from_pyobj(&x2,x2_capi,"endf6.yintp() 3rd argument (x2) can't be converted to double");
    if (f2py_success) {
    /* Processing variable y2 */
        f2py_success = double_from_pyobj(&y2,y2_capi,"endf6.yintp() 4th argument (y2) can't be converted to double");
    if (f2py_success) {
    /* Processing variable i */
        f2py_success = int_from_pyobj(&i,i_capi,"endf6.yintp() 5th argument (i) can't be converted to int");
    if (f2py_success) {
    /* Processing variable x */
        f2py_success = double_from_pyobj(&x,x_capi,"endf6.yintp() 6th argument (x) can't be converted to double");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&yintp,&x1,&y1,&x2,&y2,&i,&x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",yintp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of x*/
    /* End of cleaning variable x */
    } /*if (f2py_success) of i*/
    /* End of cleaning variable i */
    } /*if (f2py_success) of y2*/
    /* End of cleaning variable y2 */
    } /*if (f2py_success) of x2*/
    /* End of cleaning variable x2 */
    } /*if (f2py_success) of y1*/
    /* End of cleaning variable y1 */
    } /*if (f2py_success) of x1*/
    /* End of cleaning variable x1 */
    /* End of cleaning variable yintp */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of yintp ********************************/

/************************************ yleg ************************************/
static char doc_f2py_rout_endf6_yleg[] = "\
yleg = yleg(x,a,na)\n\nWrapper for ``yleg``.\
\n\nParameters\n----------\n"
"x : input float\n"
"a : input rank-1 array('d') with bounds (*)\n"
"na : input int\n"
"\nReturns\n-------\n"
"yleg : float";
/* extern void F_WRAPPEDFUNC(yleg,YLEG)(double*,double*,double*,int*); */
static PyObject *f2py_rout_endf6_yleg(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double yleg = 0;
    double x = 0;
    PyObject *x_capi = Py_None;
    double *a = NULL;
    npy_intp a_Dims[1] = {-1};
    const int a_Rank = 1;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int na = 0;
    PyObject *na_capi = Py_None;
    static char *capi_kwlist[] = {"x","a","na",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:endf6.yleg",\
        capi_kwlist,&x_capi,&a_capi,&na_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable yleg */
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.yleg: failed to create array from the 2nd argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable x */
        f2py_success = double_from_pyobj(&x,x_capi,"endf6.yleg() 1st argument (x) can't be converted to double");
    if (f2py_success) {
    /* Processing variable na */
        f2py_success = int_from_pyobj(&na,na_capi,"endf6.yleg() 3rd argument (na) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&yleg,&x,a,&na);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("d",yleg);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of na*/
    /* End of cleaning variable na */
    } /*if (f2py_success) of x*/
    /* End of cleaning variable x */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    /* End of cleaning variable yleg */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of yleg ********************************/

/*********************************** legndr ***********************************/
static char doc_f2py_rout_endf6_legndr[] = "\
legndr(x,p,nl)\n\nWrapper for ``legndr``.\
\n\nParameters\n----------\n"
"x : input float\n"
"p : input rank-1 array('d') with bounds (*)\n"
"nl : input int";
/* extern void F_FUNC(legndr,LEGNDR)(double*,double*,int*); */
static PyObject *f2py_rout_endf6_legndr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double x = 0;
    PyObject *x_capi = Py_None;
    double *p = NULL;
    npy_intp p_Dims[1] = {-1};
    const int p_Rank = 1;
    PyArrayObject *capi_p_as_array = NULL;
    int capi_p_intent = 0;
    PyObject *p_capi = Py_None;
    int nl = 0;
    PyObject *nl_capi = Py_None;
    static char *capi_kwlist[] = {"x","p","nl",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:endf6.legndr",\
        capi_kwlist,&x_capi,&p_capi,&nl_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable p */
    ;
    capi_p_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "endf6.endf6.legndr: failed to create array from the 2nd argument `p`";
    capi_p_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,p_Dims,p_Rank,  capi_p_intent,p_capi,capi_errmess);
    if (capi_p_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = endf6_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        p = (double *)(PyArray_DATA(capi_p_as_array));

    /* Processing variable x */
        f2py_success = double_from_pyobj(&x,x_capi,"endf6.legndr() 1st argument (x) can't be converted to double");
    if (f2py_success) {
    /* Processing variable nl */
        f2py_success = int_from_pyobj(&nl,nl_capi,"endf6.legndr() 3rd argument (nl) can't be converted to int");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&x,p,&nl);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of nl*/
    /* End of cleaning variable nl */
    } /*if (f2py_success) of x*/
    /* End of cleaning variable x */
    if((PyObject *)capi_p_as_array!=p_capi) {
        Py_XDECREF(capi_p_as_array); }
    }  /* if (capi_p_as_array == NULL) ... else of p */
    /* End of cleaning variable p */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of legndr *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"mf4_get_leg",-1,{{-1}},0,0,(char *)  F_FUNC_US(mf4_get_leg,MF4_GET_LEG),  (f2py_init_func)f2py_rout_endf6_mf4_get_leg,doc_f2py_rout_endf6_mf4_get_leg},
    {"yintp",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC(yintp,YINTP),  (f2py_init_func)f2py_rout_endf6_yintp,doc_f2py_rout_endf6_yintp},
    {"yleg",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC(yleg,YLEG),  (f2py_init_func)f2py_rout_endf6_yleg,doc_f2py_rout_endf6_yleg},
    {"legndr",-1,{{-1}},0,0,(char *)  F_FUNC(legndr,LEGNDR),  (f2py_init_func)f2py_rout_endf6_legndr,doc_f2py_rout_endf6_legndr},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "endf6",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_endf6(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = endf6_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module endf6 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.1.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'endf6' is auto-generated with f2py (version:2.1.1).\nFunctions:\n"
"    mf4_get_leg(awr,awi,awp,q,lct,e1,a1,nl1,e2,a2,nl2,ilaw,e,xmu,nmu,f4,ne=shape(f4, 0))\n"
"    yintp = yintp(x1,y1,x2,y2,i,x)\n"
"    yleg = yleg(x,a,na)\n"
"    legndr(x,p,nl)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.1.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    endf6_error = PyErr_NewException ("endf6.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_endf6_error", endf6_error);
    Py_DECREF(endf6_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


    {
      extern double F_FUNC(yintp,YINTP)(void);
      PyObject* o = PyDict_GetItemString(d,"yintp");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(yintp,YINTP),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("yintp");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

    {
      extern double F_FUNC(yleg,YLEG)(void);
      PyObject* o = PyDict_GetItemString(d,"yleg");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(yleg,YLEG),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("yleg");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"endf6");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
