C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.1.1)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapyintp (yintpf2pywrap, x1, y1, x2, y2, i, 
     &x)
      external yintp
      real*8 x1
      real*8 y1
      real*8 x2
      real*8 y2
      integer i
      real*8 x
      real*8 yintpf2pywrap
      real*8  yintp
      yintpf2pywrap = yintp(x1, y1, x2, y2, i, x)
      end


      subroutine f2pywrapyleg (ylegf2pywrap, x, a, na)
      external yleg
      real*8 x
      integer na
      real*8 a(*)
      real*8 ylegf2pywrap
      real*8  yleg
      ylegf2pywrap = yleg(x, a, na)
      end

