C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.1.1)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapf6law1_con (f6law1_conf2pywrap, e, tp, w,
     & za, zai, zap, lang, lep, nd, na, nep, ep, b)
      external f6law1_con
      real*8 e
      real*8 tp
      real*8 w
      real*8 za
      real*8 zai
      real*8 zap
      integer lang
      integer lep
      integer nd
      integer na
      integer nep
      real*8 ep(*)
      real*8 b(nep,*)
      real*8 f6law1_conf2pywrap
      real*8  f6law1_con
      f6law1_conf2pywrap = f6law1_con(e, tp, w, za, zai, zap, lang
     &, lep, nd, na, nep, ep, b)
      end


      subroutine f2pywrapf6law1_dis (f6law1_disf2pywrap, e, tp, w,
     & za, zai, zap, lang, nd, na, nep, ep, b)
      external f6law1_dis
      real*8 e
      real*8 tp
      real*8 w
      real*8 za
      real*8 zai
      real*8 zap
      integer lang
      integer nd
      integer na
      integer nep
      real*8 ep(*)
      real*8 b(nep,*)
      real*8 f6law1_disf2pywrap
      real*8  f6law1_dis
      f6law1_disf2pywrap = f6law1_dis(e, tp, w, za, zai, zap, lang
     &, nd, na, nep, ep, b)
      end


      subroutine f2pywrapihigh (ihighf2pywrap, x0, x, i0, n)
      external ihigh
      real*8 x0
      integer i0
      integer n
      real*8 x(*)
      integer ihighf2pywrap
      integer  ihigh
      ihighf2pywrap = ihigh(x0, x, i0, n)
      end


      subroutine f2pywrapimatch (imatchf2pywrap, x0, x, n)
      external imatch
      real*8 x0
      integer n
      real*8 x(*)
      integer imatchf2pywrap
      integer  imatch
      imatchf2pywrap = imatch(x0, x, n)
      end


      subroutine f2pywrapyintp (yintpf2pywrap, x1, y1, x2, y2, i, 
     &x)
      external yintp
      real*8 x1
      real*8 y1
      real*8 x2
      real*8 y2
      integer i
      real*8 x
      real*8 yintpf2pywrap
      real*8  yintp
      yintpf2pywrap = yintp(x1, y1, x2, y2, i, x)
      end


      subroutine f2pywraptab1intp (tab1intpf2pywrap, x, y, np, nbt
     &, ibt, nr, x0)
      external tab1intp
      integer np
      integer nr
      real*8 x0
      real*8 x(*)
      real*8 y(*)
      integer nbt(*)
      integer ibt(*)
      real*8 tab1intpf2pywrap
      real*8  tab1intp
      tab1intpf2pywrap = tab1intp(x, y, np, nbt, ibt, nr, x0)
      end


      subroutine f2pywrapunit_base_intp (unit_base_intpf2pywrap, y
     &1, x1, f1, np1, nbt1, ibt1, nr1, y2, x2, f2, np2, nbt2, ibt2, nr2,
     & inty, y0, x0)
      external unit_base_intp
      real*8 y1
      integer np1
      integer nr1
      real*8 y2
      integer np2
      integer nr2
      integer inty
      real*8 y0
      real*8 x0
      real*8 x1(*)
      real*8 f1(*)
      integer nbt1(*)
      integer ibt1(*)
      real*8 x2(*)
      real*8 f2(*)
      integer nbt2(*)
      integer ibt2(*)
      real*8 unit_base_intpf2pywrap
      real*8  unit_base_intp
      unit_base_intpf2pywrap = unit_base_intp(y1, x1, f1, np1, nbt
     &1, ibt1, nr1, y2, x2, f2, np2, nbt2, ibt2, nr2, inty, y0, x0)
      end


      subroutine f2pywrapyleg (ylegf2pywrap, x, a, na)
      external yleg
      real*8 x
      integer na
      real*8 a(*)
      real*8 ylegf2pywrap
      real*8  yleg
      ylegf2pywrap = yleg(x, a, na)
      end


      subroutine f2pywrapykalbach (ykalbachf2pywrap, zai, zap, zat
     &, e, ep, u, b, na)
      external ykalbach
      real*8 zai
      real*8 zap
      real*8 zat
      real*8 e
      real*8 ep
      real*8 u
      integer na
      real*8 b(*)
      real*8 ykalbachf2pywrap
      real*8  ykalbach
      ykalbachf2pywrap = ykalbach(zai, zap, zat, e, ep, u, b, na)
      end


      subroutine f2pywrapbachaa (bachaaf2pywrap, zai, zap, zat, ee
     &, epe)
      external bachaa
      real*8 zai
      real*8 zap
      real*8 zat
      real*8 ee
      real*8 epe
      real*8 bachaaf2pywrap
      real*8  bachaa
      bachaaf2pywrap = bachaa(zai, zap, zat, ee, epe)
      end

